spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/user_center
#    hikari:
#      username: root
#      password: 12345678
#      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-center
  cloud:
    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - optional:nacos:user-center-dev.yaml
#  sleuth:
#    sampler:
#      probability: 1.0
#  zipkin:
#    base-url: http://127.0.0.1:9411
#    discovery-client-enabled: false

#server:
#  port: 8000

#rocketmq:
#  name-server: 127.0.0.1:9876

#jwt:
#  secret: LJxN8hH0ncEEyuxxMM6nOxVuzxSuXQ2ZQYQSRVnl1Z0nRC7jIwnVFN9HyT2lidpjnkxYqb
#  expire: 1209600
