spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: root
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: content-center
    cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080

server:
  port: 8010


feign:
  client:
    config:
      user-center:
        logger-level: full
  httpclient:
    max-connections: 30
    max-connections-per-route: 10
  # feign整合sentinel后dashborad的资源名称中会带上微服务名
  sentinel:
    enabled: true

logging:
  level:
    com.deng.contentcenter.feignclient.UserCenterFeignClient: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'

