spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: root
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: content-center
    cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848

server:
  port: 8010
