spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/content_center
#    hikari:
#      username: root
#      password: 12345678
#      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: content-center

  config:
    import:
      - optional:nacos:content-center-dev.yaml
#  sleuth:
#    sampler:
#      probability: 1.0
#  zipkin:
#    base-url: http://127.0.0.1:9411
#    discovery-client-enabled: false
  cloud:
#    sentinel:
#      transport:
#        dashboard: localhost:8080
    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
#server:
#  port: 8010


#feign:
#  client:
#    config:
#      user-center:
#        logger-level: full
#      default:
#        requestInterceptors:
#          - com.deng.contentcenter.feignclient.interceptor.TokenRelayRequestInterceptor
#  httpclient:
#    max-connections: 30
#    max-connections-per-route: 10
#  # feign整合sentinel后dashborad的资源名称中会带上微服务名
#  sentinel:
#    enabled: true

logging:
  level:
    com.deng.contentcenter.feignclient.UserCenterFeignClient: DEBUG
    com.deng.contentcenter.dao.content: DEBUG


#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#rocketmq:
#  name-server: 127.0.0.1:9876
#  producer:
#    group: test-group

#jwt:
#  secret: LJxN8hH0ncEEyuxxMM6nOxVuzxSuXQ2ZQYQSRVnl1Z0nRC7jIwnVFN9HyT2lidpjnkxYqb
#  expire: 1209600

#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true